### ISSUE TITLE
Testing the dc_dgl installation result prompts ''CUDA: an illegal memory access was encountered''

### ISSUE THREAD

**Issue by lzc17** [initzhang/dc_dgl#3]
![image](https://github.com/initzhang/dc_dgl/assets/41893135/3544475d-4b76-4909-a064-a4b38209325e)

**Comment by initzhang** [comment]
Hi, I have updated the test script, could you try again?

**Comment by lzc17** [comment]
This problem occurred.
![image](https://github.com/initzhang/dc_dgl/assets/41893135/f09fe5bc-c046-4a82-a581-5531aeead5c7)

**Comment by initzhang** [comment]
could you provide more details about your software and hardware settings?

**Comment by lzc17** [comment]
conda list：
![image](https://github.com/initzhang/dc_dgl/assets/41893135/72aeee65-9cf8-4787-8cca-de23cda6bea8)
CPU information：
![image](https://github.com/initzhang/dc_dgl/assets/41893135/967bea90-62e7-485b-95dd-b498261e11c7)

**Comment by lzc17** [comment]
GPU：NVIDIA k80

**Comment by lzc17** [comment]
Can we not use the sampling results to judge whether the installation is successful because the sampling results change?
The following are two sampling results：
![image](https://github.com/initzhang/dc_dgl/assets/41893135/695e7efb-18f5-4419-a492-60be16b46f90)

**Comment by initzhang** [comment]
Indeed for your case, the installation is actually successful, and I think you can move on to the rest of ducati repo safely. As for the sampling result comparison, this is rather a (maybe too rigid) safety insurance. I will check what is going on and maybe improve this part later. Thank you for your report!

**Comment by lzc17** [comment]
Thanks, I will close this question.

**Comment by lzc17** [comment]
The following error occurs when running ‘run_allocate.py’:
![image](https://github.com/initzhang/dc_dgl/assets/41893135/de9f6e96-5750-4b5e-8904-add2462a18ab)

**Comment by lzc17** [comment]
The following error occurs when running ‘run_allocate.py’:
![image](https://github.com/initzhang/dc_dgl/assets/41893135/de9f6e96-5750-4b5e-8904-add2462a18ab)

**Comment by initzhang** [comment]
[The line of code](https://github.com/initzhang/DUCATI_SIGMOD/blob/376f79da2f291ceffcc6311b34c247cd09fb2bb3/load_graph.py#L133) (load_graph.py L133) which causes your error is a standard DGL-UVA code without any modification. 

```
# load_graph.py
...
126   sampler = dgl.dataloading.NeighborSampler(fanouts)
...
133             input_nodes, output_nodes, blocks = sampler.sample(graph, seeds)
...
```

What is your result of `python run_sota.py`?

**Comment by lzc17** [comment]
There was an issue with UVA sampling with the 0.8.0 version of DGL using the k80 GPU, which was resolved before I upgraded to 1.0.2.

**Comment by lzc17** [comment]
run 'run_sota.py' result:
![image](https://github.com/initzhang/dc_dgl/assets/41893135/ba6e4c13-dc88-4887-bb22-d3eec792c9fd)

**Comment by initzhang** [comment]
Got it, then it seems that the problem is caused by using K80 with DGL v0.8 which is unfortunately our code base ([related issues](https://github.com/dmlc/dgl/issues/4726) in DGL, DGLv0.8 has some glitches about using UVA on old GPUs with computing capability < 6). Since several other people have successfully reproduced this repo with other GPUs, and we do not have future plan to rebase/refactor our code against new DGL releases, is it possible for you to try other GPU cards?
